carried_items = {'slot1': {'item': 'Sword'}, 
                 'slot2': {'item': 'nothing'},
                 'slot3': {'item': 'nothing'},
                 'slot4': {'item': 'nothing'},
                 'slot5': {'item': 'nothing'},
                 'slot6': {'item': 'nothing'},
                 'slot7': {'item': 'nothing'},
                 'slot8': {'item': 'nothing'},
                 'slot9': {'item': 'nothing'},
                 'slot10': {'item': 'nothing'},}